{
 "title": "Shimmer Dashboard",
 "time": { "from": "2025-08-25T14:12:01.946Z", "to": "2025-08-25T14:12:11.895Z" },
 "panels": [
  {
   "title": "Magnetometer",
   "type": "timeseries",
   "description": "Lokales Magnetfeld, bestimmt Ausrichtung relativ zum Erdmagnetfeld",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": " from(bucket: \"facialReco\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"shimmer3gsrplus\" and\n    contains(value: r._field, set: [\"Mag_X_CAL\", \"Mag_Y_CAL\", \"Mag_Z_CAL\" ])\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Puls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": " from(bucket: \"facialReco\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"shimmer3gsrplus\" and\n    contains(value: r._field, set: [\"PPG_Rate\" ])\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Accelerometer",
   "type": "timeseries",
   "description": "Misst Beschleunigung in alle Richtungen",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": " from(bucket: \"facialReco\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"shimmer3gsrplus\" and\n    contains(value: r._field, set: [\"Accel_LN_X_CAL\", \"Accel_LN_Y_CAL\", \"Accel_LN_Z_CAL\", \"Accel_WR_X_CAL\", \"Accel_WR_Y_CAL\", \"Accel_WR_Z_CAL\" ])\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Gyroskop",
   "type": "timeseries",
   "description": "Misst die Winkelgeschwindigkeit, ermöglicht Bestimmung der Körperorientierung und Analyse von Drehbewegungen. ",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"facialReco\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"shimmer3gsrplus\" and\n    contains(value: r._field, set: [\"Gyro_X_CAL\", \"Gyro_Y_CAL\", \"Gyro_Z_CAL\"])\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}