{
 "title": "Telemetrie Systems",
 "time": { "from": "2025-08-04T15:09:16.000Z", "to": "2025-08-04T15:16:21.000Z" },
 "panels": [
  {
   "title": "ABS & TC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"csv_import\" and\n    contains(value: r._field, set: [\"ABS Active\", \"TC Active\"])\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "KERS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"csv_import\" and\n    contains(value: r._field, set: [\"KERS Charge\", \"KERS Deployed Energy\", \"KERS Input\"])\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "DRS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"csv_import\" and\n    contains(value: r._field, set: [\"DRS Active\", \"DRS Available\"])\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "ERS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"csv_import\" and\n    contains(value: r._field, set: [\"ERS Is Charging\"])\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Lap Distance ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"csv_import\" and\n    contains(value: r._field, set: [\"Lap Distance\"])\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}