{
 "title": "Telemetrie",
 "time": { "from": "2025-08-04T15:09:16.515Z", "to": "2025-08-04T15:16:21.310Z" },
 "panels": [
  {
   "title": "Gang",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"csv_import\" and\n    contains(value: r._field, set: [\"Gear\"])\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n\n"
    }
   ]
  },
  {
   "title": "Gas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"csv_import\" and\n    r._field == \"Throttle Pos\"\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Reifen Belastung ",
   "type": "timeseries",
   "description": "Angegebene in Newton ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"csv_import\" and\n    contains(value: r._field, set: [\"Tire Load FL\", \"Tire Load FR\", \"Tire Load RL\", \"Tire Load RR\"])\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Geschwindigkeit (nach Tacho)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"csv_import\" and\n    r._field == \"Ground Speed\"\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n"
    },
    {}
   ]
  },
  {
   "title": "Bremse ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"csv_import\" and\n    r._field == \"Brake Pos\"\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Lenkeinschlag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"csv_import\" and\n    r._field == \"Steering Angle\"\n  )\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n"
    }
   ]
  }
 ]
}